### ISSUE TITLE
no CNN Explainer running in broswer 

### ISSUE THREAD

**Issue by homingZhang** [poloclub/cnn-explainer#13]
Hi, I have download git and npm,
and the cnn-explainer was downloaded successfully,
then I used npm run dev, it showed "you application is ready" !
![1](https://user-images.githubusercontent.com/30250401/83584977-3a8b7580-a57b-11ea-859f-e705f9b0954f.png)

but when I input "localhost:5000" in my broswer, there is nothing in my broswer,
![2](https://user-images.githubusercontent.com/30250401/83584987-3e1efc80-a57b-11ea-8440-141bbc9575ec.png)

I don't know where was wrong.
Please help me, thank you.

**Comment by xiaohk** [comment]
Could you please check if there is any error message in the browser console?

To open the Chrome console on Windows, you can use shortcut <kbd>control + shift + j</kbd>.

**Comment by homingZhang** [comment]
It's okay now, and I don't know why it's ok. I didn't find any error message in the browser console, and Thanks anyway! 
![3](https://user-images.githubusercontent.com/30250401/83601822-eea0f680-a5a3-11ea-8b9d-631c6203359e.png)

**Comment by xiaohk** [comment]
Awesome! No problem.

**Comment by jnumingdeli** [comment]
When I run it locally, it shows Your Application is ready~!", but when I open the browser, the interface is chaotic, how do I solve it?Thank you very much!!
![image](https://user-images.githubusercontent.com/62462594/103022630-5b530100-4587-11eb-8be9-4d51334c3d41.png)
![image](https://user-images.githubusercontent.com/62462594/103022747-8fc6bd00-4587-11eb-9247-3f110762c6e1.png)
