### ISSUE TITLE
Why is the interface blank?

### ISSUE THREAD

**Issue by lsyic** [poloclub/cnn-explainer#16]
Your work is really good!
I want to study it, but the browser interface is blank.How could I fix the problem? Thank you!!!
![image](https://user-images.githubusercontent.com/43415196/84482145-cd3dba00-acc9-11ea-8080-c0515c946d58.png)

**Comment by xiaohk** [comment]
Thanks @lsyic , I'm glad you like it!

Are you running CNN Explainer from the [public demo](https://poloclub.github.io/cnn-explainer/)? I just tested it and there is no problem loading the visualization on my machine (macOS + Firefox).

The error message indicates that it's a tensorflow.js error — It has trouble using the GPU on your machine. Below are two related issues:

https://github.com/tensorflow/tfjs/issues/1466
https://github.com/justadudewhohacks/face-api.js/issues/282

I suggest updating your browser (looks like Chrome?) to the latest version and try to load [CNN Explainer](https://poloclub.github.io/cnn-explainer/) again.

**Comment by lsyic** [comment]
Yeah!It's browser's problem. 
The software running well after updating the browser.
Thank you!!!

**Comment by xiaohk** [comment]
Good! No problem ٩( ᐛ )و
