### ISSUE TITLE
If I want to show my model, where should I change it

### ISSUE THREAD

**Issue by xyLpf** [poloclub/cnn-explainer#17]

**Comment by xiaohk** [comment]
You can check out issues #2, #8, #15.

Some functions you want to look into first are listed [here](https://github.com/poloclub/cnn-explainer/issues/8#issuecomment-624624004).

If you only want to train Tiny-VGG on a new dataset, you can also check out issue #14.

I will close the issues for now. Feel free to reach out if you need further help :)
