### ISSUE TITLE
how to see myself model

### ISSUE THREAD

**Issue by fengxiuyaun** [poloclub/cnn-explainer#2]
thank you very much, I can not find any turorial how to see myself model.

**Comment by TopGun666** [comment]
> thank you very much, I can not find any turorial how to see myself model.

+1

**Comment by xiaohk** [comment]
@fengxiuyaun @TopGun666 Thanks for asking! We are using a pre-trained Tiny VGG for pedagogical purpose, to help beginners learn the underlying concepts of CNNs. We are sorry that CNN Explainer doesn't support users to visualize their own models at this moment.

**Comment by wdzwdxy** [comment]
我使用tiny—vgg训练完成自己的模型后，使用tfjs生成了两个文件，group1-shard1of.bin   and    model.json   
接下来需要如何操作
（我尝试替换了在public目录下的data目录中的文件，但是在cnnexplainer中并没有展示出，本应在网络处展示的内容为空白）
