### ISSUE TITLE
Can I use cnn-explainer on auto-encoder model?

### ISSUE THREAD

**Issue by jkren6** [poloclub/cnn-explainer#20]
I'm currently using a deep auto-encoder model to learn state representation from the pixel, can I use this cnn-explainer to get a better understanding of the training process? 

If so, what changes should be made? Could u please give me some guidlines~ 

Thanks 😁

**Comment by xiaohk** [comment]
Hello, thanks for using CNN Explainer!

It can be a little tricky to adapt CNN Explainer to CNN-based autoencoder models. The system currently supports explaining convolutional, ReLU, max-pool, flatten, and softmax layers. You would need to create visualizations to explain transposed convolutional layers and the reparameterization layers (if it is VAE).

To see which functions you need to change, you can check out https://github.com/poloclub/cnn-explainer/issues/8#issuecomment-624624004.

I would close the issue for now, let me know if you have other questions :)
