### ISSUE TITLE
Did you ever think to make a plugin like this for pytorch or tensorflow

### ISSUE THREAD

**Issue by destructive-observer** [poloclub/cnn-explainer#23]
dear wang:
    Your cnn-explainer is very impressive for my study,thank you sou much.However,did you ever think to make a plugin like this for pytorch or tensorflow.so the research could visualize their cnn work procedure clearly.This is only my suggestion,thank so much for your cnn-explainer.

**Comment by xiaohk** [comment]
Thank you so much for using CNN Explainer! We are glad it is helpful for your study :)

The main goal of CNN Explainer is to help beginners get started with CNNs. Plugins for PyTorch or TensorFlow will focus on  helping machine learning engineers debug or interpret their models. CNN Explainer would need to be significantly modified to achieve that goal. We plan to adapt the designs of CNN Explainers in our future projects that are designed for more experienced users. Plugins sound very cool!

In the mean time, you can also check out our other interactive tool [summit](https://github.com/fredhohman/summit) which is designed for ML model interpretability.

I will close the issue for now. Feel free to re-open or comment if you have more suggestions or questions.
