### ISSUE TITLE
Pop-up window is too small

### ISSUE THREAD

**Issue by xiers819** [poloclub/cnn-explainer#29]
Hello! Thank you for your contribution!
I find that the pop-up window of details is too small to see the details on my laptop screen. Can I make the window full screen or zoom it in?

![2021-04-16_171811](https://user-images.githubusercontent.com/42505191/115003556-8071d380-9ed8-11eb-95af-f129338f0c18.png)

**Comment by xiaohk** [comment]
Hey, good comment! I will consider to make the pop-up window resizable and perhaps draggable.

For now to make it larger, you can just use the zoom in functionality of your browser.

https://user-images.githubusercontent.com/15007159/115016608-47f3da80-9e83-11eb-94d3-95e1637e5394.mp4
