### ISSUE TITLE
run with static ip

### ISSUE THREAD

**Issue by johnfelipe** [poloclub/cnn-explainer#30]
HOST=ip npm run dev

is another way more secure or quick for setup?

**Comment by xiaohk** [comment]
Hello @johnfelipe,

Are you asking if there are other more ways to set up CNN Explainer? The command `nom run dev` compiles the code in `watch` mode and sets up a local server from the `public` folder inside CNN Explainer. It is secure and quick.

You can also run `npm run build` to bundle the CNN Explainer code and set up your own web server from the `public` folder.
