### ISSUE TITLE
ReLu function max(0,a) gives 0

### ISSUE THREAD

**Issue by jeromecy** [poloclub/cnn-explainer#33]
Using Ladybug pic as an example, the ReLU function after the top one layer (orange colour) gives 0 when the max value is not zero. For example, I got max(0,0.64)=0. Should it be 0.64? Thank you.

**Comment by xiaohk** [comment]
Hello @jeromecy, thanks for reaching out to us!

In which ReLU layer did you see the `max(0, 0.64)=0` case?

I am looking at the `relu_2_2` layer for the laydybug pic and it looks correct.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/15007159/144265105-14ad3e89-f0b0-46a1-8ea3-26a515fe2a2c.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/15007159/144265169-2c3bcd60-643f-4a63-bfbe-abb2cf4bfea3.png">

**Comment by jeromecy** [comment]
Hi @xiaohk , many thanks for the reply. I apologies that it was my bad. The negative sign is too small on my screen, and I didn't notice it. After zooming in, I can see it clearly. Thank you so much!

**Comment by xiaohk** [comment]
Hey @jeromecy, you should not apologize! It's a legit usability issue, and we should apologize for the confusion. Thanks again for raising the issue so we can improve the design!

In b9c1759050033850d4245d1a85bb74c475aa377e I changed the original `-` sign (`Hyphen-Minus`) to a longer `－` sign (`Fullwidth Hyphen-Minus`). I hope it can help. Below is a before and after comparison.

![image](https://user-images.githubusercontent.com/15007159/144350659-82b74f20-df32-4a1a-a9a3-c77f5fdfec21.png)
![image](https://user-images.githubusercontent.com/15007159/144351308-f986995f-c7f9-4413-b92c-536eb0f3996f.png)
