### ISSUE TITLE
Update the number of layer

### ISSUE THREAD

**Issue by davy-blavette** [poloclub/cnn-explainer#37]
Hey @xiaohk, Thank you for your answer. The solution was simpler, I just had an error in the generation of my model.json file, with a shape at 1690 for 10 layers instead of 1183 for 7 ... 
However, I had to adapt lines :
replace :
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L859
```python
for (let i = 0; i < nodeCoordinate[curLayerIndex - 1].length; i++) {
```
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L879
```python
textY = nodeCoordinate[curLayerIndex - 1][nodeCoordinate[curLayerIndex - 1].length - 1].y + nodeLength / 2;
```
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L345
```python
let loopFactors = [0, nodeCoordinate[curLayerIndex - 1].length - 1];
```
after add :
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L998-L1002
```python
let maxLayer = nodeCoordinate[curLayerIndex - 1].length - 1;
```
replace :
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L1096
```python
let bottomY = nodeCoordinate[curLayerIndex - 1][maxLayer].y + nodeLength -
```
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/flatten-draw.js#L345
```python
let loopFactors = [0, maxLayer];
```
https://github.com/poloclub/cnn-explainer/blob/b9c1759050033850d4245d1a85bb74c475aa377e/src/overview/overview-draw.js#L649-L650
```python
svgPaddings.top + vSpaceAroundGap * (classLists.length) + vSpaceAroundGap +
nodeLength * classLists.length
```

It's ok it works perfectly. Good job !

_Originally posted by @davy-blavette in https://github.com/poloclub/cnn-explainer/discussions/36#discussioncomment-1777823_

**Comment by xiaohk** [comment]
Great work @davy-blavette ! Thanks for sharing your steps here. I am sure it will be very helpful for other users. I will close the issue now.

The original post is in the discussion panel: https://github.com/poloclub/cnn-explainer/discussions/36
