### ISSUE TITLE
question about changing parameter 'height'

### ISSUE THREAD

**Issue by baobobby** [poloclub/cnn-explainer#38]
Hi @xiaohk, I successfully managed to make cnn-explainer show a model with more layers and now I'm trying to make it work with model that has a different value of filter. I set the filter to 20 and put this new model in the cnn-explainer, the intermediate view and detail view work just as expected, but nodes are overlapping with eachother. 
![屏幕截图 2021-12-20 230544](https://user-images.githubusercontent.com/83474816/146838962-000974dd-83f6-402a-a517-2368a9d25783.jpg)

I checked the code in overview-draw.js and it shows:
```
    vSpaceAroundGap = (height - nodeLength * curLayer.length) / (curLayer.length + 1);

```
I think an overlay maybe means a negativ vSpaceAroundGap, so what I can do is to change the parameter 'height' but what should I do?

**Comment by xiaohk** [comment]
Sorry for the super late reply. I have been busy with some other work :(

The `height` is determined by user's screen size:

https://github.com/poloclub/cnn-explainer/blob/2b75d287704c8a7134a99798cd3b771e896337fc/src/overview/Overview.svelte#L1310

You can get the value in javascript like:

```js
Number(d3.select('#cnn-svg').style('height').replace('px', ''))
```

Let me know if it doesn't solve your problem. I will close the issue now.
