### ISSUE TITLE
error in npm run dev

### ISSUE THREAD

**Issue by huangpan2507** [poloclub/cnn-explainer#39]
(base) yosunpeng@server:~/cnn-explainer$ npm run dev

> svelte-app@1.0.0 dev /home/yosunpeng/cnn-explainer
> rollup -c -w

sh: 1: rollup: not found

npm ERR! Linux 5.3.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! svelte-app@1.0.0 dev: `rollup -c -w`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 dev script 'rollup -c -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the svelte-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs svelte-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls svelte-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yosunpeng/cnn-explainer/npm-debug.log

**Comment by xiaohk** [comment]
Hello @huangpan2507, sorry for the late reply!

You can try to run `npm install` before `npm run dev`. 

Let me know if it doesn't solve your problem. I will close the issue for now.
