### ISSUE TITLE
failed to create enviroment

### ISSUE THREAD

**Issue by MHandZQ** [poloclub/cnn-explainer#4]
![`X}4{FQY19(H{JQW1A42AC4](https://user-images.githubusercontent.com/30924400/80917186-ed579080-8d8f-11ea-8706-1b9c9ed1eca2.png)

**Comment by xiaohk** [comment]
Thanks for raising up this issue!

It's my bad that the packages listed in `environment.yaml` were specific to the macOS build. I have updated the file in the [dev branch](https://github.com/poloclub/cnn-explainer/blob/master/tiny-vgg/environment.yaml). Could you please try again and let me know if it fixes this issue?

**Comment by MHandZQ** [comment]
**still failed**
![image](https://user-images.githubusercontent.com/30924400/80931786-a51b8b00-8dee-11ea-86d9-a47e609a7e8e.png)

**Comment by xiaohk** [comment]
How about [this version](https://github.com/poloclub/cnn-explainer/blob/dev/tiny-vgg/environment.yaml)?

**Comment by MHandZQ** [comment]
successfully craeted enviroment,but I found another problem
![image](https://user-images.githubusercontent.com/30924400/80944632-99df5400-8e1c-11ea-9a08-37764b49064f.png)

**Comment by MHandZQ** [comment]
thanks for your help,the problem is solved.but I found another problem:
when I execute import tensorflow as tf  there is a mistake 
![image](https://user-images.githubusercontent.com/30924400/80958727-061b8100-8e38-11ea-8cce-1e5eb9533f8f.png)

**Comment by MHandZQ** [comment]
Is it a compatibility issue between MACos and Windows? so the version of tensorflow is not compatible?

**Comment by xiaohk** [comment]
Did you activate the conda environment using `conda activate tiny-vgg`?

If yes: the tensorflow you installed should be windows compatible; I don't have a windows machine so I can't test it. Can you please try to follow the [instruction](https://www.tensorflow.org/install) to see if you can install and use tensorflow 2 outside of this conda environment?

**Comment by MHandZQ** [comment]
Thanks for your help.You can solve this problem by using low version of tensorflow.
I have successfully trained tiny-vgg and convert the model file from Keras h5 format to tensorflow.js format,but could you tell me how  to use tensorflow.js to load the trained model.

**Comment by xiaohk** [comment]
Awesome!! 🎉 

Sure! The [tensorflow.js documentation](https://www.tensorflow.org/js/guide/save_load) can be very helpful. Below I listed some related functions in CNN Explainer:

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/overview/Overview.svelte#L1116-L1117

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L414-L422

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L55-L231

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L233-L270

I will close this issue for now. Feel free to ask away if you have any other questions :P
