### ISSUE TITLE
vue中无法运行

### ISSUE THREAD

**Issue by ChenWeiJiaGitHub** [poloclub/cnn-explainer#40]
当我运行程序的时候就会报错，也不知道是什么原因，哪位大神帮忙指点迷津，谢谢！
D:\works\qianduan\ywgz-mini-program>npm run dev
npm ERR! Windows_NT 10.0.19042
npm ERR! argv "D:\\software\\node\\node_new\\node.exe" "C:\\Users\\86152\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ru
n" "dev"
npm ERR! node v16.14.0
npm ERR! npm  v3.8.6
npm ERR! path D:\works\qianduan\ywgz-mini-program\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\works\qianduan\ywgz-mini-program\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\works\qianduan\ywgz-mini-program\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\works\qianduan\ywgz-mini-program\npm-debug.log

**Comment by xiaohk** [comment]
Hello @ChenWeiJiaGitHub!

Make sure you are running from the `cnn-explainer` directory (there should be a [`package.json` file](https://github.com/poloclub/cnn-explainer/blob/master/package.json))
Then you need to run `npm install` before `npm run dev`. 

Let me know if it doesn't solve your problem. I will close the issue for now.

**Comment by ChenWeiJiaGitHub** [comment]
好了，谢谢你！
