### ISSUE TITLE
更换图片重新训练后却没有变化

### ISSUE THREAD

**Issue by Yan-heng** [poloclub/cnn-explainer#43]
为什么更换了图片重新训练之后，生成的bin文件和model.json文件将原来的两个文件替换之后，用npm run dev打开网页之后却没有变化，不是图片没有变换而是训练的结果output没有变换

**Comment by MrDenial** [comment]
https://github.com/poloclub/cnn-explainer/issues/8

**Comment by xiaohk** [comment]
Sorry for the late reply! Make sure you clean up the browser cache when you replace the model files. I will close the issue for now. Let me know if it does not fix the problem.

**Comment by Yan-heng** [comment]
yep,the problem is fixed right now.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jay ***@***.***&gt;; 
发送时间: 2022年5月30日(星期一) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [poloclub/cnn-explainer] 更换图片重新训练后却没有变化 (Issue #43)





 
Sorry for the late reply! Make sure you clean up the browser cache when you replace the model files. I will close the issue for now. Let me know if it does not fix the problem.
