### ISSUE TITLE
Why is the page empty

### ISSUE THREAD

**Issue by TOM-ZXian** [poloclub/cnn-explainer#45]
![image](https://user-images.githubusercontent.com/30914694/171988275-0431163e-0fa7-4661-992a-e796b64cddea.png)

**Comment by xiaohk** [comment]
Hello @TOM-ZXian! I think there were some hiccups on the `cdn.jsdelivr.net` server. You can try to refresh the page after some time.

I will close the issue for now. Feel free to reopen if the problem persists.

**Comment by Anindya18081010098** [comment]
Hi! the page is still not show The Explainer!
But the rest of the page is fine!
![image](https://user-images.githubusercontent.com/71441723/195323675-10633952-b300-4118-b121-b007402030f2.png)
