### ISSUE TITLE
How we can explain neuron if we do use cnn?

### ISSUE THREAD

**Issue by M-Amrollahi** [poloclub/cnn-explainer#47]
How we can explain the neural networks when we do not apply cnn?
For example in Tensorflow Playground, how do they illustrate the neuron in each layer?

**Comment by xiaohk** [comment]
Hello @M-Amrollahi, sorry for the late reply.

CNN Explainer is designed for CNNs. If you want to illustrate neurons in a dense neural network, you can check out Tensorflow Playground. It uses a heatmap to visualize a neuron by plotting its output values over a 2D grid.
