### ISSUE TITLE
Relu layer bug

### ISSUE THREAD

**Issue by minglou1984** [poloclub/cnn-explainer#5]
![image](https://user-images.githubusercontent.com/37362398/80990973-e309c500-8e69-11ea-84b4-06b420f0a81b.png)
There is a bug in the max of the Relu layer here

**Comment by minglou1984** [comment]
The pixel value is negative, too small, I did n’t see it clearly

**Comment by xiaohk** [comment]
Thats a good point! (๑•̀ㅂ•́)و✧

Thank you for bringing this to our attention. We will fix it in later versions.
