### ISSUE TITLE
HTTP ERROR 403

### ISSUE THREAD

**Issue by Latiest** [poloclub/cnn-explainer#50]
When I run the application npm run dev, open the localhost:5000 at edge, it return HTTP ERROR 403.How can I figure it out?

**Comment by xiaohk** [comment]
Hello @Latiest , sorry for the late response.

Did you run `npm install` before `npm run dev`?

**Comment by Latiest** [comment]
yes, I run `npm install`, then I run `npm run dev`. It returns 403

**Comment by xiaohk** [comment]
I see. I guess it is because macOS now occupies port 5000.

Can you please try to run `npx sirv public --single --dev --port 3000` and local [localhost:3000](http://localhost:3000) in your browser?

**Comment by Latiest** [comment]
Ok. Is running successfully now. Thanks a lot.

**Comment by xiaohk** [comment]
Nice! Thanks for reporting this error. I changed the default port number from 5000 to 3000 in 6214bdebdc2f81045724c54c2cc7a9b0d4b0400c.
