### ISSUE TITLE
a suggestion for Deployment on server

### ISSUE THREAD

**Issue by Yun-Tianming** [poloclub/cnn-explainer#55]
Original package.json is not friendly for deploment.  We need to use the IP (e.g., 64.69.41.183:3000) instead of localhost (e.g., localhost:3000) to allow accessing the server's webpage through a local browser. Specifically, it's crucial to modify the code in the package.json file.
```
--------before-------------------------------
"scripts": {
"build": "rollup -c",
"dev": "rollup -c -w",
"start": "sirv public --single",
"start:dev": "sirv public --single --dev --port 3000",
"deploy": "npx"
}

------after-------------------------------------------
"scripts": {
  "build": "rollup -c",
  "dev": "rollup -c -w",
  "start": "sirv public --single --host 0.0.0.0",
  "start:dev": "sirv public --single --dev --host 0.0.0.0 --port 3000",
  "deploy": "npx"
}
```

[see more](https://circular-kettle-026.notion.site/CNN-Explainer-II-Deployment-Background-Process-Retention-and-Domain-Proxy-6caaa37251584ae0b3d4e1a9c631eb7b?pvs=4)

**Comment by xiaohk** [comment]
Thanks for the suggestion! Future users can refer to this issue to configure the deployment IP and host.
