### ISSUE TITLE
What should I do if I want to change the model?

### ISSUE THREAD

**Issue by shxiangyan** [poloclub/cnn-explainer#8]

**Comment by xiaohk** [comment]
Hello, this is related to #2. 

Currently CNN Explainer only supports the Tiny-VGG architecture that we described in our [manuscript](http://arxiv.org/abs/2004.15004). If you want to use a different CNN model, then you would need to modify the code. If you want to use another pre-trained Tiny-VGG  model, you can see the following functions in CNN Explainer (how we use tensorflow.js to load the model):

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/overview/Overview.svelte#L1116-L1117

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L414-L422

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L55-L231

https://github.com/poloclub/cnn-explainer/blob/0a6e09ea5548f97160b93b925a883f35a7d5b80e/src/utils/cnn-tf.js#L233-L270

Let us know if you have more questions. I will close the issue for now :P

**Comment by EricCousineau-TRI** [comment]
As an FYI, docs for converting to `TensorFlow.js` models:
https://www.tensorflow.org/js/tutorials#convert_pretrained_models_to_tensorflowjs
